# Generated by Django 4.2.16 on 2024-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cio_event_cio_project_cio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cio',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='cio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cio',
            name='members',
        ),
        migrations.AlterField(
            model_name='cio',
            name='image',
            field=models.ImageField(upload_to='cios/'),
        ),
        migrations.AlterField(
            model_name='cio',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
