# Generated by Django 4.2.16 on 2024-11-14 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_remove_cio_admins_remove_cio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cio',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_cios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cio',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_cios', to=settings.AUTH_USER_MODEL),
        ),
    ]
