# Generated by Django 4.2.16 on 2024-12-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_adminfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cios/'),
        ),
    ]
