# Generated by Django 4.2.16 on 2024-12-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_announcement'),
        ('users', '0017_alter_cio_image'),
    ]

    operations = [
    ]
