# Generated by Django 4.2.16 on 2024-12-05 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_file_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
